---
packages: 
  - ansible
  - vim
  - neofetch
  - speedtest-cli
  - solaar
  - gnome-tweaks

custom_bashrc: |
  export PS1="\e[32m\u@\h\e[0m:\e[34m[\w]\e[0m:\e[33m\$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')\n\e[0m$ \[$(tput sgr0)\]"
